/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;
import org.antlr.v4.runtime.*;
import parser.JFTTLexer;
import parser.JFTTParser;

public class App {

    public static void main(String[] args){
        //Parsing program parameters
        BaseArgParser argumentParser = new ArgParser();
        argumentParser.parse(args);

        //Creating Lexer
        JFTTLexer lexer = new JFTTLexer(argumentParser.getCharStream());
        JFTTParser parser = new JFTTParser(new CommonTokenStream(lexer));

        //Running parser
        ParserManager parserManager = new ParserManager();
        parserManager.addErrorDetector(new VariableRedefinitionErrorDetector());
        parserManager.addErrorDetector(new UndeclaredVariableErrorDetector());
        parserManager.runAll(parser);

        if(parserManager.getErrors().size()>0) {
            //Printing errors
            System.out.println(parserManager.printErrors());
            return;
        }
        else{
            //Printing the symbolTable
            System.out.println(parserManager.printSymbolTable());

            //Generate code
            //...
        }




    }
}